trigger:
  - main # Se dispara automáticamente al hacer push a la rama main

pool:
  vmImage: 'windows-2022'

variables:
  proyecto: '**/*.csproj'
  buildConfiguration: 'Release'
  dotnetVersion: '10.0.x'

stages:
# 1. ETAPA DE COMPILACIÓN (CI)
- stage: Build
  displayName: 'Compilación y Publicación'
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '$(proyecto)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# 2. ETAPA DE DESPLIEGUE (CD)
- stage: Deploy
  displayName: 'Despliegue a Azure App Service'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'jabrielth07-PortfolioDJ' # Nombre de la conexión
        appType: 'webApp'
        appName: 'Portafolio-DJ'    # Nombre de tu App Service
        package: '$(System.ArtifactsDirectory)/drop/*.zip'